sitemap:
  pattern: /sitemap.xml
  defaults:     { _controller: OpenSkySitemapBundle:Sitemap:sitemap, _format: xml }
  requirements: { _method: GET }
siteindex:
  pattern: /siteindex.xml
  defaults:     { _controller: OpenSkySitemapBundle:Sitemap:siteindex, _format: xml }
  requirements: { _method: GET }